app_base: 
  appid: "wx6da0ac0db0ae0bfa"
  app_secret: ""

jwt_info:
  jwt_sec: "allthingscomfrom2022winter"
  jwt_maxage: 7 #days

dsn: "root:@tcp(localhost:3307)/flagger?charset=utf8&parseTime=True&loc=Local"

db: 
  user: root
  password: intoflagger1@
  host: 10.0.224.16:3306
  dbname: flagger
